const actionTypes: AnalyticsNS.IActionTypes = {
    ANALYTICS_SET_INITIAL_DATA: 'ANALYTICS_SET_INITIAL_DATA',
    ANALYTICS_SET_DATES: 'ANALYTICS_SET_DATES',
    ANALYTICS_SET_ARRANGE_COLUMNS: 'ANALYTICS_SET_ARRANGE_COLUMNS',
    ANALYTICS_SET_LOADER: 'ANALYTICS_SET_LOADER',
    ANALYTICS_SET_COLUMN_FILTERS: 'ANALYTICS_SET_COLUMN_FILTERS',
};

export default actionTypes;